// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int N = Integer.parseInt(args[0]);
	int i = 0;
	int countBig = 0;
	int countSmall = 0;
	while (i < N) {
		double ran = Math.random();
		if (ran < 0.5) {
			countBig++;
		} else {
			countSmall++;
	    }
		i++;	
	}
	System.out.println("> 0.5: " + " " + countBig + "  times");
	System.out.println("<= 0.5: " + countSmall + " times");
	// Dealing withe the ratio and edge case:
	double ratio = 0.0;
	if (countBig == countSmall) {
		ratio = 1.0;
		System.out.println("Ratio: " + ratio);	
	} else if (countBig == 0 || countSmall == 0) {
		System.out.println("An edge case (division by zero)");
	} else if (countBig > countSmall) {
		 ratio = (double) countSmall  / countBig;
		 System.out.println("Ratio: " + ratio);
	} else if (countSmall > countBig ) {
		 ratio = (double) countBig / countSmall;
		 System.out.println("Ratio: " + ratio); 
	}	
 }
}
	
  



